version: '3.3'

services:
  cherissaknol:
    container_name: cherissaknol
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      - NEXTAUTH_SECRET=
      - USERNAME=
      - PASSWORD=
      - GMAIL_USER=
      - GMAIL_PASSWORD=
    volumes:
      - ../prisma/database:/app/prisma/database

  # cherissaknol:
  #   image: robinkuiper/cherissaknol:latest
  #   container_name: cherissaknol
  #   ports:
  #     - 8082:8082
  #   environment:
  #     - NEXTAUTH_SECRET=
  #     - USERNAME=
  #     - PASSWORD=
  #     - GMAIL_USER=
  #     - GMAIL_PASSWORD=
  #   restart: unless-stopped
