import Head from 'next/head';
import { Layout, Title } from '../components';

const collabs = () => {
  return (
    <Layout>
      <Head>
        <title>Collabs - Cherissa Knol</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Title>Collabs</Title>

      {/* <button>Open Modal</button> */}

      {/* <div className="fixed bg-[rgba(0,0,0,0.9)] z-50 inset-0" style={{}}></div> */}
    </Layout>
  );
};

export default collabs;
