import Head from 'next/head';
import { Layout, Title } from '../components';

const collabs = () => {
  return (
    <Layout>
      <Head>
        <title>Collabs - Cherissa Knol</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Title>Collabs</Title>
    </Layout>
  );
};

export default collabs;
