import Head from 'next/head';
import { Layout } from '../components';

const about = () => {
  return (
    <Layout>
      <Head>
        <title>About Me - Cherissa Knol</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div>About</div>
    </Layout>
  );
};

export default about;
