import Head from 'next/head';
import { FaEnvelope, FaFacebook, FaInstagram, FaPhone } from 'react-icons/fa';
import { Layout, Title } from '../components';
import { ContactForm } from '../components/contact/ContactForm';

const Contact = () => {
  return (
    <Layout>
      <Head>
        <title>Contact - Cherissa Knol</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div className="sm:flex flex-row mt-10 sm:pr-40">
        <div className="sm:w-2/4">
          <div className="flex flex-col items-center space-y-8">
            <Title>My Socials</Title>
            <a
              href="mailto:pietje@jan.nl"
              className="text-xl flex flex-row space-x-4 items-center"
            >
              <FaEnvelope className="text-orange-400" />
              <span>test@example.com</span>
            </a>
            <a
              href="tel:1234567891"
              className="text-xl flex flex-row space-x-4"
            >
              <FaPhone className="text-orange-400" />
              <span>123-456-7891</span>
            </a>
            <p className="flex space-x-8 justify-center text-4xl">
              <FaFacebook className="cursor-pointer hover:text-orange-400 hover:scale-110" />
              <FaInstagram className="cursor-pointer hover:text-orange-400 hover:scale-110" />
            </p>
          </div>

          <div className="mt-10 sm:mt-36 text-xs flex flex-col items-center">
            <p className="text-sm">Company</p>
            <p>KVK: 123456789</p>
            <p>BTW: 123456789</p>
          </div>
        </div>
        <div className="sm:w-2/4 mt-10 sm:mt-0">
          <Title className="text-center sm:text-left">Get In Touch</Title>
          <ContactForm />
        </div>
      </div>
    </Layout>
  );
};

export default Contact;
