import Head from 'next/head'
import { Layout } from '../components'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Cherissa Knol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Blaat</h1>
    </Layout>
  )
}
